Journal Browse page
highwire/Generic-Patternlab pull request #7
Opened 2021-06-28 10:13 UTC by ashwanisrivastav

2021-06-28 11:26 UTC, vinothk-hw commented on source/_patterns/03-components/site/_home.scss
>          margin: 0rem 0;
Please check the style margin is used one time...

2021-06-28 11:26 UTC, vinothk-hw commented on source/_patterns/03-components/site/_journal-browse.scss
> +
Requesting please check unwanted spacing to removed before making PR.

2021-06-28 11:26 UTC, vinothk-hw commented on source/_patterns/03-components/site/_subject-browse.scss
> +  @extend .about;
May i know why u r extending from about page instead of generic style?

2021-06-28 11:26 UTC, vinothk-hw commented on source/_patterns/03-components/site/journal-browse.twig
> -	<div class="container">
should not bind in container. Please check the condition its should render only components. Please create seperate element after condition...

2021-06-28 11:28 UTC, ashwanisrivastav commented on source/_patterns/02-molecules/grouping/_pagination.scss
> +      border-color: #94b1b7;
this color code is not available in variables

2021-06-28 11:31 UTC, vinothk-hw commented on source/_patterns/02-molecules/grouping/_pagination.scss
> +      border-color: #94b1b7;
if not available then create in variable and call in scss. We are working in theme concept we should not call anything statically(Color, font-family, Size ect..)

2021-06-28 12:55 UTC, ashwanisrivastav commented on source/_patterns/02-molecules/grouping/_pagination.scss
> +    display: block;
fixed

2021-06-28 12:55 UTC, ashwanisrivastav commented on source/_patterns/02-molecules/grouping/_pagination.scss
> +      border-color: #94b1b7;
fixed

2021-06-28 12:55 UTC, ashwanisrivastav commented on source/_patterns/02-molecules/grouping/_pagination.scss
> +
fixed

2021-06-28 14:39 UTC, ashwanisrivastav commented on source/_patterns/03-components/site/_subject-browse.scss
> +  @extend .about;
beacause of same spacing

2021-06-28 14:43 UTC, ashwanisrivastav commented on source/_patterns/03-components/site/journal-browse.twig
> -	<div class="container">
container  is not rendering in journal-browse-page.

2021-06-28 14:49 UTC, ashwanisrivastav commented on source/_patterns/03-components/site/_home.scss
>          margin: 0rem 0;
fixed

2021-06-28 14:50 UTC, ashwanisrivastav commented on source/_patterns/02-molecules/grouping/pagination.twig
> +		<a class="pagination__page-link feather-chevron-left" href="#" tabindex="-1" aria-disabled="true"></a>
done

2021-06-29 08:11 UTC, vinothk-hw requested changes

2021-06-30 05:42 UTC, vinothk-hw approved these changes
Looks good...

2021-06-30 06:00 UTC, merged